$(document).ready(function(){
    $('.sidebar-buton').click(function(){
        $('.sidebar').toggleClass('active');
        $('.sidebar').toggleClass('togle');
    })
})
$(document).ready(function(){
    $('.rule').click(function(){
        $('.rule-container').toggleClass('activve');
        $('.rule-container').toggleClass('togle');
    })
})